# Generated by Django 4.0.2 on 2022-02-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('podhod', models.IntegerField()),
                ('povtor', models.IntegerField()),
                ('weight_work', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('level1', models.BooleanField(default=False)),
                ('level2', models.BooleanField(default=False)),
                ('level3', models.BooleanField(default=False)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.practice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
