# Generated by Django 4.0.2 on 2022-02-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='level1',
            new_name='es',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='level2',
            new_name='hd',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='level3',
            new_name='md',
        ),
    ]
